### 1. Write a Python Program to Add Two Matrices?

In [6]:
import numpy as np
A= np.array([[1,2,3],[4,5,6]] ) 
B= np.array([[7,8,9],[2,3,6]] )
C=A+B
C

array([[ 8, 10, 12],
       [ 6,  8, 12]])

### 2. Write a Python Program to Multiply Two Matrices?

In [7]:
import numpy as np
A= np.array([[1,2,3],[4,5,6]] ) 
B= np.array([[7,8,9],[2,3,6]] )
C=A*B
C

array([[ 7, 16, 27],
       [ 8, 15, 36]])

### 3. Write a Python Program to Transpose a Matrix?

In [8]:
A= np.array([[1,2,3],[4,5,6]] ) 
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])


### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [13]:
n= input("Enter the string")
words= (n.lower()).split()
words.sort()
words

Enter the string I am a good girl


['a', 'am', 'girl', 'good', 'i']

### 5. Write a Python Program to Remove Punctuation From a String?

In [23]:
import string
 
pun= "!(,)-[]#$%^&*{>/?@};:'"
my_str = input("Enter a string: ")  
 
no_punct = ""  
for char in my_str:  
   if char not in pun:  
       no_punct = no_punct + char  

print(no_punct)  


Enter a string:  a vjhhk, []hjbjh


a vjhhk hjbjh
